package dnsutils

import "github.com/miekg/dns"

// DnsTypes references https://en.wikipedia.org/wiki/List_of_DNS_record_types

type DnsType string

var DnsTypes = map[uint16]DnsType{
	dns.TypeA:          "A",
	dns.TypeNS:         "NS",
	dns.TypeMD:         "MD",
	dns.TypeMF:         "NF",
	dns.TypeCNAME:      "CNAME",
	dns.TypeSOA:        "SOA",
	dns.TypeMB:         "MB",
	dns.TypeMG:         "MG",
	dns.TypeMR:         "MR",
	dns.TypeNULL:       "NULL",
	dns.TypePTR:        "PTR",
	dns.TypeHINFO:      "HINFO",
	dns.TypeMINFO:      "MINFO",
	dns.TypeMX:         "MX",
	dns.TypeTXT:        "TXT",
	dns.TypeRP:         "RP",
	dns.TypeAFSDB:      "AFSDB",
	dns.TypeX25:        "X25",
	dns.TypeISDN:       "ISDN",
	dns.TypeRT:         "RT",
	dns.TypeNSAPPTR:    "NSAPPTR",
	dns.TypeSIG:        "SIG",
	dns.TypeKEY:        "KEY",
	dns.TypePX:         "PX",
	dns.TypeGPOS:       "GPOS",
	dns.TypeAAAA:       "AAAA",
	dns.TypeLOC:        "LOC",
	dns.TypeNXT:        "NTX",
	dns.TypeEID:        "EID",
	dns.TypeNIMLOC:     "NIMLOC",
	dns.TypeSRV:        "SRV",
	dns.TypeATMA:       "ATMA",
	dns.TypeNAPTR:      "NAPTR",
	dns.TypeKX:         "KX",
	dns.TypeCERT:       "CERT",
	dns.TypeDNAME:      "DNAME",
	dns.TypeOPT:        "OPT",
	dns.TypeAPL:        "APL",
	dns.TypeDS:         "DS",
	dns.TypeSSHFP:      "SSHFP",
	dns.TypeRRSIG:      "RRSIG",
	dns.TypeNSEC:       "NSEC",
	dns.TypeDNSKEY:     "DNSKEY",
	dns.TypeDHCID:      "DHCID",
	dns.TypeNSEC3:      "NSEC3",
	dns.TypeNSEC3PARAM: "NSEC3PARAM",
	dns.TypeTLSA:       "TLSA",
	dns.TypeSMIMEA:     "SMIMEA",
	dns.TypeHIP:        "HIP",
	dns.TypeNINFO:      "NINFO",
	dns.TypeRKEY:       "RKEY",
	dns.TypeTALINK:     "TALINK",
	dns.TypeCDS:        "CDS",
	dns.TypeCDNSKEY:    "CDNSKEY",
	dns.TypeOPENPGPKEY: "OPENPGPKEY",
	dns.TypeCSYNC:      "CSYNC",
	dns.TypeZONEMD:     "ZONEMD",
	dns.TypeSVCB:       "SVCB",
	dns.TypeHTTPS:      "HTTPS",
	dns.TypeSPF:        "SPF",
	dns.TypeUINFO:      "UINFO",
	dns.TypeUID:        "UID",
	dns.TypeGID:        "GID",
	dns.TypeUNSPEC:     "UNSPEC",
	dns.TypeNID:        "NID",
	dns.TypeL32:        "L32",
	dns.TypeL64:        "L64",
	dns.TypeLP:         "LP",
	dns.TypeEUI48:      "EUI48",
	dns.TypeEUI64:      "EUI64",
	dns.TypeURI:        "URI",
	dns.TypeCAA:        "CAA",
	dns.TypeAVC:        "AVC",
}
